development:
  access_key_id: AKIAJY7TE7TS3ZZVIIDA
  secret_access_key: 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

production:
  access_key_id: AKIAJY7TE7TS3ZZVIIDA
  secret_access_key: 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